-- Copyright (c) Altera Corporation, 1996. This file may contain proprietary and confidential
-- information of Altera Corporation that may be used, copied, and disclosed only pursuant to
-- the terms of Altera's Program License Agreement. Altera makes no claim to any end-user or
-- third-party proprietary information that also may be contained in this file. This notice
-- must be contained as part of this text at all times.

-- MAX+plus II Include File
-- Version 7.0 RC2 08/21/96
-- Created: Mon Sep 09 13:56:35 1996

FUNCTION fft_over (data[3..0],clk)
    RETURNS (dist[1..0]);
